using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.0.1.0")]
[assembly: AssemblyCopyrightAttribute("Austin Foam Plastic, 2011")]
[assembly: AssemblyProductAttribute("EdiDocsProcessing")]
[assembly: AssemblyCompanyAttribute("Austin Foam Plastic")]
[assembly: AssemblyConfigurationAttribute("debug")]
[assembly: AssemblyInformationalVersionAttribute("0.0.1.0")]

